version: "3.9"
services:
    database:
        container_name: jalvadev_db
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=jalvadev_admin
            - POSTGRES_PASSWORD=/run/secrets/db-password
            - POSTGRES_DB=jalvadev
        volumes:
            - "C:/Data/jalvadev:/var/lib/postgresql/data"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U jalvadev_admin -d jalvadev"]
            interval: 10s
            retries: 3
            start_period: 30s
            timeout: 30s
    backend:
        container_name: jalvadev_backend
        build:
            context: ./jalvadev-back
        ports:
            - 8080:8080
        depends_on:
            database:
                condition: service_healthy
        develop:
            watch:
                - action: rebuild
                  path: .
secrets:
    db-password:
        file: passwords.txt