version: "3.9"
services:
    database:
        container_name: jalvadev_db
        image: postgres:latest
        ports:
            - 5432:5432
        secrets:
            - db-password
        environment:
            - POSTGRES_USER=jalvadev_admin
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
            - POSTGRES_DB=jalvadev
        volumes:
            - "C:/Data/jalvadev:/var/lib/postgresql/data"
            - "./database/init.sql:/docker-entrypoint-initdb.d/init.sql"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U jalvadev_admin -d jalvadev"]
            interval: 10s
            retries: 3
            start_period: 30s
            timeout: 30s
    backend:
        container_name: jalvadev_backend
        build:
            context: ./jalvadev-back
        ports:
            - 8080:8080
        environment:
            - DOTNET_ENVIRONMENT=Staging
        secrets:
            - db-password
        depends_on:
            database:
                condition: service_healthy
        develop:
            watch:
                - action: rebuild
                  path: .
    frontend:
        container_name: jalvadev_front
        build:
            context: ./jalvadev-front
        ports:
            - 4000:4000
        depends_on:
            - backend
secrets:
    db-password:
        file: passwords.txt