//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jalvadev_back.Resources
{
    using System;
    using System.Reflection;
    using System.Resources;

    public class Resource
    {
        private static ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    resourceMan = new ResourceManager("jalvadev_back.Resources.Resource", Assembly.GetExecutingAssembly());
                }
                return resourceMan;
            }
        }

        public static string api_error_bd_connection
        {
            get
            {
                return ResourceManager.GetString("api_error_bd_connection", resourceCulture);
            }
        }

        public static string api_error_password_file_not_found
        {
            get
            {
                return ResourceManager.GetString("api_error_password_file_not_found", resourceCulture);
            }
        }

        public static string ui_error_getting_project
        {
            get
            {
                return ResourceManager.GetString("ui_error_getting_project", resourceCulture);
            }
        }

        public static string ui_error_getting_post
        {
            get
            {
                return ResourceManager.GetString("ui_error_getting_post", resourceCulture);
            }
        }

        public static string ui_error_getting_post_list
        {
            get
            {
                return ResourceManager.GetString("ui_error_getting_post_list", resourceCulture);
            }
        }

        public static string ui_error_getting_user
        {
            get
            {
                return ResourceManager.GetString("ui_error_getting_user", resourceCulture);
            }
        }
        public static string ui_error_post_list_empty
        {
            get
            {
                return ResourceManager.GetString("ui_error_post_list_empty", resourceCulture);
            }
        }
        
        public static string ui_error_getting_tags
        {
            get
            {
                return ResourceManager.GetString("ui_error_getting_tags", resourceCulture);
            }
        }

        public static string ui_error_post_not_found
        {
            get
            {
                return ResourceManager.GetString("ui_error_post_not_found", resourceCulture);
            }
        }

        public static string ui_error_project_not_found
        {
            get
            {
                return ResourceManager.GetString("ui_error_project_not_found", resourceCulture);
            }
        }

        public static string ui_error_tag_not_found
        {
            get
            {
                return ResourceManager.GetString("ui_error_tag_not_found", resourceCulture);
            }
        }

        public static string ui_error_user_not_found
        {
            get
            {
                return ResourceManager.GetString("ui_error_user_not_found", resourceCulture);
            }
        }


    }
}
